card_names = [
    [
        'Wild',
        '6 of Diamonds',
        '7 of Diamonds',
        '8 of Diamonds',
        '9 of Diamonds',
        '10 of Diamonds',
        'Queen of Diamonds',
        'King of Diamonds',
        'Ace of Diamonds',
        'Wild'
    ],
    [
        '5 of Diamonds',
        '3 of Hearts',
        '2 of Hearts',
        '2 of Spades',
        '3 of Spades',
        '4 of Spades',
        '5 of Spades',
        '6 of Spades',
        '7 of Spades',
        'Ace of Clubs'
    ],
    [
        '4 of Diamonds',
        '4 of Hearts',
        'King of Diamonds',
        'Ace of Diamonds',
        'Ace of Clubs',
        'King of Clubs',
        'Queen of Clubs',
        '10 of Clubs',
        '8 of Spades',
        'King of Clubs'
    ],
    [
        '3 of Diamonds',
        '5 of Hearts',
        'Queen of Diamonds',
        'Queen of Hearts',
        '10 of Hearts',
        '9 of Hearts',
        '8 of Hearts',
        '9 of Clubs',
        '9 of Spades',
        'Queen of Clubs'
    ],
    [
        '2 of Diamonds',
        '6 of Hearts',
        '10 of Diamonds',
        'King of Hearts',
        '3 of Hearts',
        '2 of Hearts',
        '7 of Hearts',
        '8 of Clubs',
        '10 of Spades',
        '10 of Clubs'
    ],
    [
        'Ace of Spades',
        '7 of Hearts',
        '9 of Diamonds',
        'Ace of Hearts',
        '4 of Hearts',
        '5 of Hearts',
        '6 of Hearts',
        '7 of clubs',
        'Queen of Spades',
        '9 of clubs'
    ],
    [
        'King of Spades',
        '8 of Hearts',
        '8 of Diamonds',
        '2 of Clubs',
        '3 of Clubs',
        '4 of Clubs',
        '5 of Clubs',
        '6 of Clubs',
        'King of Spades',
        '8 of Clubs'],
    [
        'Queen of Spades',
        '9 of Hearts',
        '7 of Diamonds',
        '6 of Diamonds',
        '5 of Diamonds',
        '4 of Diamonds',
        '3 of Diamonds',
        '2 of Diamonds',
        'Ace of Spades',
        '7 of Clubs'
    ],
    [
        '10 of Spades',
        '10 of Hearts',
        'Queen of Hearts',
        'King of Hearts',
        'Ace of Hearts',
        '2 of Clubs',
        '3 of Clubs',
        '4 of Clubs',
        '5 of Clubs',
        '6 of Clubs'
    ],
    [
        'Wild',
        '9 of Spades',
        '8 of Spades',
        '7 of Spades',
        '6 of Spades',
        '5 of Spades',
        '4 of Spades',
        '3 of Spades',
        '2 of Spades',
        'Wild'
    ]]